### ISSUE TITLE
your doug esp framework

### ISSUE THREAD

**Issue by cooldude315** [AlexBurneikis/Sotdle-Daily#2]
for some reason when i load it into the game it doesnt really show me anything it just shows my fps and the normal stuff like crosshair but doesnt show me ships and people, do you know how i could fix this?

**Comment by cooldude315** [comment]
![image](https://user-images.githubusercontent.com/117041200/200121558-a245ab0b-463d-4173-a832-62022bb7fa66.png)

**Comment by burneikis** [comment]
From the image it looks like you are missing the "config.json" file. Just looking at ur terminal there you may have moved some files around from the source code, I would recommend just downloading the raw source code and then running "python main.py" from there.

Also, this repo is for Sotdle, if you have any other issues I would prefer if you opened them in "Sot-DLC"

**Comment by cooldude315** [comment]
> From the image it looks like you are missing the "config.json" file. Just looking at ur terminal there you may have moved some files around from the source code, I would recommend just downloading the raw source code and then running "python main.py" from there.
> 
> Also, this repo is for Sotdle, if you have any other issues I would prefer if you opened them in "Sot-DLC"

for some reason, it won't let me make a pull request inside sot-DLC, but quick question when I load into the game is it supposed to show where my ship is and my teammates and other enemies or just enemies and have canon aimbot? becuase when i load the main.py it just shows me the crosshair and the normal fps and "dougdruid..." but isnt it supposed to show other things or did you make it like that? but i open the main.py in pycharm (seems to be the only way main.py loads for me)

**Comment by cooldude315** [comment]
> > From the image it looks like you are missing the "config.json" file. Just looking at ur terminal there you may have moved some files around from the source code, I would recommend just downloading the raw source code and then running "python main.py" from there.
> > Also, this repo is for Sotdle, if you have any other issues I would prefer if you opened them in "Sot-DLC"
> 
> for some reason, it won't let me make a pull request inside sot-DLC, but quick question when I load into the game is it supposed to show where my ship is and my teammates and other enemies or just enemies and have canon aimbot? becuase when i load the main.py it just shows me the crosshair and the normal fps and "dougdruid..." but isnt it supposed to show other things or did you make it like that? but i open the main.py in pycharm (seems to be the only way main.py loads for me)

also i havent changed anything

**Comment by cooldude315** [comment]
![image](https://user-images.githubusercontent.com/117041200/200372492-4cb5cae4-6d28-4785-ab6d-b7725a1e54fa.png)

**Comment by cooldude315** [comment]
i did as done and it worked but isnt it suppose to show ships and players? 
![image](https://user-images.githubusercontent.com/117041200/200373959-6320a39c-c663-4a0a-aedb-d1286bac18fa.png)

does it show teamates and my crews ship or no, and how does the canon aimbot work? or is it when i get close it will show becuase the only things that show up is the fps thing and doug druid and the crosshair

**Comment by burneikis** [comment]
It should show players and teammates within 150-300m and ships within ~3000. It only works if you get into a server and then run it.
