### ISSUE TITLE
Cant open a issue inside sot-dlc

### ISSUE THREAD

**Issue by cooldude315** [AlexBurneikis/Sotdle-Daily#3]

**Comment by burneikis** [comment]
I think it should work now

**Comment by cooldude315** [comment]
> I think it should work now

what happened to sot-dlc?

**Comment by burneikis** [comment]
https://github.com/DougTheDruid/SoT-ESP-Framework

**Comment by cooldude315** [comment]
> https://github.com/DougTheDruid/SoT-ESP-Framework

thats dougs esp, the core, what happened to ur esp?

**Comment by burneikis** [comment]
Doug opened an issue in which he very kindly asked that I private the repo, his reasons are explained in the readme of his framework.

**Comment by cooldude315** [comment]
oh :(

**Comment by cooldude315** [comment]
is there a way you could make the private repo like visible for me?

> Doug opened an issue in which he very kindly asked that I private the repo, his reasons are explained in the readme of his framework.

Is there a way you could make the private repo visible for me only :)

**Comment by cooldude315** [comment]
do you have discord

**Comment by burneikis** [comment]
Yes

**Comment by cooldude315** [comment]
> Yes

can i contact you with it

**Comment by burneikis** [comment]
Sure

**Comment by AlexBurneikis** [comment]
@cooldude315 Sponge#2234
